name: Sync upstream changes

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 3:00 UTC
  workflow_dispatch:     # Allow manual runs

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/cupcakearmy/cryptgeon.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Push changes to your fork
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create Pull Request to custom branch
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated upstream sync"
          title: "Sync upstream changes into rival-it-custom"
          body: "This PR merges the latest upstream changes into your custom branch."
          base: rival-it-custom
          branch: main 